export const routes = {
  eCommerce: {
    dashboard: "/inventory",
    products: "/inventory/products",
    createProduct: "/inventory/products/create",
    productDetails: (slug: string) => `/inventory/products/${slug}`,
    ediProduct: (slug: string) => `/inventory/products/${slug}/edit`,
    categories: "/inventory/categories",
    createCategory: "/inventory/categories/create",
    editCategory: (id: string) => `/inventory/categories/${id}/edit`,
    orders: "/inventory/orders",
    createOrder: "/inventory/orders/create",
    orderDetails: (id: string) => `/inventory/orders/${id}`,
    editOrder: (id: string) => `/inventory/orders/${id}/edit`,
    reviews: "/inventory/reviews",
    shop: "/inventory/shop",
    cart: "/inventory/cart",
    checkout: "/inventory/checkout",
    trackingId: (id: string) => `/inventory/tracking/${id}`,
  },
  searchAndFilter: {
    realEstate: "/search/real-estate",
    nft: "/search/nft",
    flight: "/search/flight",
  },
  support: {
    dashboard: "/support",
    inbox: "/support/inbox",
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: "/support/snippets",
    createSnippet: "/support/snippets/create",
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: "/support/templates",
    createTemplate: "/support/templates/create",
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: "/logistics",
    shipmentList: "/logistics/shipments",
    customerProfile: "/logistics/customer-profile",
    createShipment: "/logistics/shipments/create",
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  appointment: {
    dashboard: "/appointment",
    appointmentList: "/appointment/list",
  },
  executive: {
    dashboard: "/executive",
  },
  jobBoard: {
    dashboard: "/job-board",
    jobFeed: "/job-board/feed",
  },
  analytics: "/analytics",
  financial: {
    dashboard: "/financial",
  },
  file: {
    dashboard: "/file",
    manager: "/file-manager",
    upload: "/file-manager/upload",
    create: "/file-manager/create",
  },
  pos: {
    index: "/point-of-sale",
  },
  eventCalendar: "/event-calendar",
  rolesPermissions: "/roles-permissions",
  invoice: {
    home: "/invoice",
    create: "/invoice/create",
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
    builder: "/invoice/builder",
  },
  widgets: {
    cards: "/widgets/cards",
    icons: "/widgets/icons",
    charts: "/widgets/charts",
    maps: "/widgets/maps",
    banners: "/widgets/banners",
  },
  tables: {
    basic: "/tables/basic",
    collapsible: "/tables/collapsible",
    enhanced: "/tables/enhanced",
    pagination: "/tables/pagination",
    search: "/tables/search",
    stickyHeader: "/tables/sticky-header",
    tanTable: "/tables/tan-table",
    tanTableResizable: "/tables/tan-table-resizable",
    tanTableDnD: "/tables/tan-table-dnd",
    tanTablePinning: "/tables/tan-table-pinning",
    tanTableEnhanced: "/tables/tan-table-enhanced",
    tanTableCollapsible: "/tables/tan-table-collapsible",
  },
  multiStep: "/multi-step",
  forms: {
    profileSettings: "forms/profile-settings",
    // notificationPreference: '/forms/profile-settings/notification',
    // personalInformation: '/forms/profile-settings/profile',
    // newsletter: '/forms/newsletter',
  },
  emailTemplates: "/email-templates",
  profile: "/profile",
  welcome: "/welcome",
  comingSoon: "/coming-soon",
  accessDenied: "/access-denied",
  notFound: "/not-found",
  maintenance: "/maintenance",
  blank: "/blank",

  dashboard: "/dashboard",
  finance: {
    allinvoices: "/finance/allinvoices",
    // todayinvoices:"/finance/todayinvoices",
    // monthlyinvoices:"/finance/monthlyinvoices",
    // expences:"/finance/expenses",
    summary: "/finance/summary",
    addpaymentmodes: "/finance/config/paymentmodes",
  },
  staff: {
    staffs: "/staff-section/staff",
    allstaffs: "/staff-section/allstaff",
    profile: "/staff-section/staff-profile",
    addstaff: "/staff-section/addstaff",
    staffattendence: "/staff-section/attendance",
  },
  Attendance: "/attendance",
  Membership: {
    list: "/membership/list",
    duelist: "/membership/due-list",
    batches: "/membership/batches",
    masterPackages: "/membership/master-packages",
    expired: "/membership/expired",
    upcomming: "/membership/upcomming-expiry",
    pt: "/membership/pt",
  },
  members: {
    list: "/members",
    new: "/members/new_member",
    attendance: "/members/member_attendance",
    // profile: (id: string) => `/member_profile/${id}` // New route added
  },
  account: {
    profile: "/profile",
    profilesettings: "/profile-settings",
  },
  attendance: "/attendance",
  auth: {
    forgotPassword: "/auth/forgot-password",
    otp: "/auth/otp",
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up-wg6ixcnunl5",
  },
  center: {
    home: "/centersettings",
    // advanced:"/centersettings/advancesettings",
    // billing:"/subscription/plans",
    contactdetails: "/centersettings/contactdetails",
    taxLegal: "/centersettings/tax&legals",
    import: "/centersettings/import",
    centers: "/centersettings/centers",
  },
  form: "/forms/profile-settings",
  gallery: "/gallery",
  gym: {
    create: "/create-gym",
  },
  newoffer: "/newoffer",
  leads: {
    leadsList: "/leads",
    leadsAdd: "/leads/new-leads",
    followupTypes: "/followups",
    leadCategories: "/leads/config/lead-categories",
    leadSources: "/leads/config/lead-sources",
    leadStatus: "/leads/config/lead-status",
  },
  sms: "/sms",
  expenses: "/expenses",
  WATemplates: "/wa-templates",
  batches: "/batches",
  enrollment: "/fee-enrollment",
  memberCategories: "/categories",
  notificationSettings: "/reminders",
  shifts: "/shifts",
  smtp: "/smtp",
  plans: "/subscription/plans",
  addons: "/subscription/addons",
  workout: {
    workoutList: "/workout",
    equipments: "/workout/equipments",
    bodyParts: "/workout/body-parts",
    exercise: "/workout/exercise",
  },
  meals: "/diet-management/meals",
  recipe: "/diet-management/recipe",
  holidays: "/holidays",
  analytic: {
    business: "/analytics",
    membership: "/analytics/membership",
    expenses: "/analytics/expense",
    members: "/analytics/member",
    enquiry: "/analytics/enquiry",
  },
  VisitingSources: "/sources",
  booking: "/booking",
  configuration: "/configuration",
  loyalty: "/loyalty-settings",
  measurements: "/measurement-settings",
  bulkMessage: "/bulk-messaging",
  logs: "/logs",
  bulkEmail: "/logs/bulk-email",
  bulkWA: "/logs/bulk-wa",
  seats: "/seats",
  books: "/books",
  bookIssuereturn: "/books/books-history",
};
